In [22]:
from datetime import datetime
import board


def populate(states):
    n_states = []
    for _ in range(states):
        instance = board.Board(5)
        n_states.append(instance)
    return n_states


def selection(pop):
    pop.sort(key=lambda state: state.get_nfit(), reverse=True)

    total_nfit = len(pop) * pop[0].maxfit
    for board in pop:
        total_nfit -= board.get_nfit()

    # normalizing fitness values
    ratios = []
    for j in pop:
        ratios.append(j.get_nfit() / total_nfit)

    # make the range for selection
    select_range = []
    fitness_level = 0
    for i in ratios:
        fitness_level += i
        select_range.append(fitness_level)

    r = np.random.uniform(0, 1)
    # return the state that the random number falls into
    if r < select_range[0]:
        return pop[0]
    elif r < select_range[1]:
        return pop[1]
    elif r < select_range[2]:
        return pop[2]
    elif r < select_range[3]:
        return pop[3]
    elif r < select_range[4]:
        return pop[4]
    elif r < select_range[5]:
        return pop[5]
    elif r < select_range[6]:
        return pop[6]
    else:
        return pop[7]

    
def crossover(gene1, gene2):
    split = random.randint(0, gene1.n_queen)
    gene1a = gene1.get_map()[:split]
    gene1b = gene1.get_map()[split:]
    gene2a = gene2.get_map()[:split]
    gene2b = gene2.get_map()[split:]

    gene1.set_map(gene1a + gene2b)
    gene2.set_map(gene2a + gene1b)

    
def mutation(gene):
    r = random.randint(0, gene.n_queen)
    if r == 0:
        return
    else:
        # set 1 to 0 first (so the Queen isn't in that position anymore)
        gene.flip(r - 1, gene.get_map()[r - 1].index(1))
        gene.flip(r - 1, random.randint(0,gene.n_queen-1))
#         gene.set_fit(0)
        gene.set_nfit(0)


def genetic(states, retries=0):
    # genetic uses non-attacking pairs, so it will be nonattacking = optimalfitness - attackingfitness from board.py
    optimal_fit = states[0].maxfit
    for i in states:
        i.nfitness()
#         i.fitness()
#         print("atk?", i.get_fit())
#         print("n atk?", i.get_nfit())
        if i.get_nfit() == optimal_fit:
            return (i, retries)
        
    selected = []
    for _ in states:
        selected.append(selection(states))

    crossover(selected[0], selected[1])
    crossover(selected[2], selected[3])
    crossover(selected[4], selected[5])
    crossover(selected[6], selected[7])

    for gene in selected:
        mutation(gene)

    return genetic(selected, retries + 1)


def main():
    ## Start the timer.
    start_time = datetime.now()
    test = populate(8)
    solution = genetic(test, retries=0)
    ## Print the runtime in milliseconds.
    print("Running Time: " + str((datetime.now() - start_time).total_seconds() * 1000) + "ms")
    print("# of restart: ", solution[1])
    solution[0].show()


if __name__ == '__main__':
    main() 
#for running x amount of tests
#     x = 100
#     counter = 1
#     for i in range(x):
#         print(counter)
#         main()
#         counter+=1


Running Time: 69.935ms
# of restart:  461
[[0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]]
Fitness:  0
